server:
  port: 8086

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 307631907025-nrsq4dog0i2bg8ll8n9akuposk8deplb.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=thecoffeehouse1
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
  flyway:
    enabled: false
    driver-class-name: org.postgresql.Driver
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

springdoc:
  swagger-ui:
    path: swagger-ui.html
    operationsSorter: method
