server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 307631907025-nrsq4dog0i2bg8ll8n9akuposk8deplb.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: false
    driver-class-name: org.postgresql.Driver
  profiles:
    active: dev
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

springdoc:
  swagger-ui:
    path: swagger-ui.html
    operationsSorter: method
